#encoding: utf-8
class DossierDecorator < ApplicationDecorator
  decorates :dossier

  %w(expo_terato ass_med_proc).each do |method|
    define_method method do
      handle_none dossier.send(method) do
        hash = array_to_hash Dossier::ONI
        hash[dossier.send(method)]
      end
    end
  end
  def age_grossesse
    handle_none dossier.age_grossesse do
      dossier.age_grossesse.to_s + " SA"
    end
  end
  def atcds_grs
    attribute = dossier.grsant
    handle_none attribute do
      if attribute == 0
        result = "primipare-primigeste"
      else
        result = attribute.to_s
        gestes = {}
        %w(fcs geu miu ivg img nai).each do |geste|
          if geste == "nai"
            gestes["naissance"] = dossier.send(geste)
          else
            gestes[geste] = dossier.send(geste)
          end
        end
        autres = []
        gestes.each do |k, v|
          if v && v > 0
            if k == "naissance"
              autres.push "#{h.pluralize(v, k)}"
            else
              autres.push v.to_s + " #{k.upcase}"
            end
          end
        end
        result += " (#{autres.to_sentence})"
      end
    end
  end

  %w(fam perso).each do |atcds|
    define_method "atcds_#{atcds}" do
      attribute = dossier.send("antecedents_#{atcds}")
      handle_none attribute do
        case attribute
        when "1" then "Aucun"
        when "0" then self.send("comm_antecedents_#{atcds}")
        else
          attribute
        end
      end
    end
  end

  %w(tabac alcool).each do |vice|
    define_method vice do
      const = vice == "tabac" ? Dossier::TABAC : Dossier::ALCOOL
      hash = array_to_hash(const)
      handle_none dossier.send(vice) do
        hash[dossier.send(vice).to_s]
      end
    end
  end

  def patiente
    handle_none dossier.patiente_fullname do
      dossier.patiente_fullname
    end
  end

  def button_to_modal
    h.link_to "#dossier_#{dossier.id}_modal", class: "btn btn-small", "data-toggle" => "modal" do
      h.safe_concat "<i class='icon-info-sign'></i>" + "\nDétails"
    end
  end

  %w(appel dernieres_regles debut_grossesse accouchement_prevu).each do |date|
    method_name = "date_#{date}"
    define_method method_name do
      handle_none dossier.send(method_name) do
        localize_date dossier.send(method_name)
      end
    end
  end

  def expositions
    handle_none dossier.produits_names, "Aucune", nil do
      twipsy dossier.produits_names
    end
  end

  private

  def method_missing (method, *args, &block)
    call = dossier.send(method, *args, &block)
    handle_none call do
      call
    end
  end

  def localize_date(datefield)
    h.l datefield
  end

  def handle_none(value, message="Non spécifié(e)", wrap="span")
    if value.present?
      yield
    else
      if wrap
        h.content_tag wrap, message, class: "none"
      else
        message
      end
    end
  end

  def twipsy(value)
    h.content_tag :a, h.truncate(value, length: 20),
      href: "#", rel: "tooltip",
      "data-original-title" => value
  end

  def array_to_hash(a)
    h = {}
    a.each do |m,n|
      h[n] = m
    end
    return h
  end

  # Accessing Helpers
  #   You can access any helper via a proxy
  #
  #   Normal Usage: helpers.number_to_currency(2)
  #   Abbreviated : h.number_to_currency(2)
  #
  #   Or, optionally enable "lazy helpers" by calling this method:
  #     lazy_helpers
  #   Then use the helpers with no proxy:
  #     number_to_currency(2)

  # Defining an Interface
  #   Control access to the wrapped subject's methods using one of the following:
  #
  #   To allow only the listed methods (whitelist):
  #     allows :method1, :method2
  #
  #   To allow everything except the listed methods (blacklist):
  #     denies :method1, :method2

  # Presentation Methods
  #   Define your own instance methods, even overriding accessors
  #   generated by ActiveRecord:
  #
  #   def created_at
  #     h.content_tag :span, time.strftime("%a %m/%d/%y"), 
  #                   :class => 'timestamp'
  #   end
end
