#encoding: utf-8
class DossierDecorator < ApplicationDecorator
  decorates :dossier

  %w(fam perso).each do |atcds|
    define_method "atcds_#{atcds}" do
      attribute = dossier.send("antecedents_#{atcds}")
      handle_none attribute do
        case attribute
        when "1" then "Aucun"
        when "0" then self.send("comm_antecedents_#{atcds}")
        else
          attribute
        end
      end
    end
  end

  def patiente
    handle_none dossier.patiente_fullname do
      dossier.patiente_fullname
    end
  end

  def button_to_modal
    h.link_to "#dossier_#{dossier.id}_modal", class: "btn btn-small", "data-toggle" => "modal" do
      h.safe_concat "<i class='icon-info-sign'></i>" + "\nDétails"
    end
  end

  def date_appel
    handle_none dossier.date_appel do
      localize_date dossier.date_appel
    end
  end

  def expositions
    handle_none dossier.produits_names, "Aucune", nil do
      twipsy dossier.produits_names
    end
  end

  private

  def method_missing (method, *args, &block)
    call = dossier.send(method, *args, &block)
    handle_none call do
      call
    end
  end

  def localize_date(datefield)
    h.l datefield
  end

  def handle_none(value, message="Non spécifié(e)", wrap="span")
    if value.present?
      yield
    else
      if wrap
        h.content_tag wrap, message, class: "none"
      else
        message
      end
    end
  end

  def twipsy(value)
    h.content_tag :a, h.truncate(value, length: 20),
      href: "#", rel: "tooltip",
      "data-original-title" => value
  end

  # Accessing Helpers
  #   You can access any helper via a proxy
  #
  #   Normal Usage: helpers.number_to_currency(2)
  #   Abbreviated : h.number_to_currency(2)
  #
  #   Or, optionally enable "lazy helpers" by calling this method:
  #     lazy_helpers
  #   Then use the helpers with no proxy:
  #     number_to_currency(2)

  # Defining an Interface
  #   Control access to the wrapped subject's methods using one of the following:
  #
  #   To allow only the listed methods (whitelist):
  #     allows :method1, :method2
  #
  #   To allow everything except the listed methods (blacklist):
  #     denies :method1, :method2

  # Presentation Methods
  #   Define your own instance methods, even overriding accessors
  #   generated by ActiveRecord:
  #
  #   def created_at
  #     h.content_tag :span, time.strftime("%a %m/%d/%y"), 
  #                   :class => 'timestamp'
  #   end
end
